### PR TITLE
Upgrade marked to 0.3.9 to fix vulnerability

### LINKED ISSUE #4: NPM module not using latest marked version, ReDoS error

### PR DESCRIPTION
**Pull request by babyhuey**
https://npmjs.com/advisories/531

### CODE REVIEW

**Comment by bryanjhv** [comment]
Hi! Thanks for taking care of security.

Could you please verify that everything still works after updating to `0.3.18`?
Github marked the package with another vulnerability at https://github.com/markedjs/marked/commit/b15e42b67cec9ded8505e9d68bb8741ad7a9590d.
That one is fixed in the specified version, and seems related to the one you just pointed out.

Thanks in advance!

**Comment by bryanjhv** [comment]
Sorry, button misclick.

**Comment by babyhuey** [comment]
Well, I tried 0.3.19, and that had more vulnerabilities fixed in >=0.6.2, so I just went all the way to 0.7.0. 

I'm not sure how to fully test, as you don't have any tests to run in your project, but I am using https://github.com/surebert/docker-ffmpeg-service and I used my updated 0.7.0, and it still rendered the readme page.

**Comment by arne-kapell** [comment]
Hey, I tried the 0.7.0 with my project and it seems to work just fine. Any chance it will be merged soon?

**Pull request merged**
